server:
  port: 8945

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: springboot
    password: iA8hE3eB5rN7wO6v
    exception-handler:
      default-exchange: exceptionHandler.defaultDirectExchange
      queues:
        bot-queues:
          name: exceptionHandler.bot-queue
          durable: true
          routing-key: bot-queue-key

logging:
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    name: logs/exception-handler.log
  level:
    org.springframework.web: ERROR
    org.hibernate: ERROR


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://pdperpusername:123456pdperpusername@localhost:8700/eureka
  instance:
    hostname: localhost



telegram:
  bot:
    username: YandexWordBot
    botToken: 1062626799:AAH5M4B7XU_9KwLEX8VEQO6Iss7gQs2e_u0
    webHookPath: https://api.telegram.org/bot1062626799:AAH5M4B7XU_9KwLEX8VEQO6Iss7gQs2e_u0/setWebhook?url=https://api.pdp.uz/api/bot/telegram
    channel-chat-id:
    group-id: -1001796540309
